language: node_js
notifications:
  email: false
node_js:
  - 8.9.1
cache:
  directories:
  - ~/.npm
  - ~/.cache
install:
  - npm install
jobs:
  include:
  - stage: "UI Tests"
    script:
    - ng test --no-watch
  - stage: "Deploy to Azure"
    script:
      - npm run build -- --mode azure
    deploy:
      provider: azure_web_apps
      site: zvm-deploymnet-1
      slot: zvm-deploymnet-1
