language: node_js
notifications:
  email: false
node_js:
  - 8.9.1
script: ng test --watch=false
cache:
  directories:
  - ~/.npm
  - ~/.cache
install:
  - npm install
before_script:
  - ls -la
  - npm install karma --save-dev
