language: node_js
notifications:
  email: false
node_js:
- 8.9.1
cache:
  directories:
  - ~/.npm
  - ~/.cache
install:
- npm install
jobs:
  include:
  - stage: "Unit Tests"
    script:
    - npm run test:unit
  #- stage: "End to End Tests"
  #  script:
  #  - npm run serve --silent &
  #  - node_modules/.bin/cypress run --record --key 02df229d-1fa9-4190-9dd3-936ee76eb721
  #- stage: "Deploy to GCP"
  #  script:
  #  - npm run build -- --mode googlecloud
  #  - export TARGET_BRANCH=$(echo $TRAVIS_BRANCH | sed -e 's/\//-/g')
  #  deploy:
  #    provider: gae
  #    keyfile: client-secret.json
  #    project: ip-teatime-evaluation-platform
  #    skip_cleanup: true
  #    on:
  #      all_branches: true
  #    version: $TARGET_BRANCH
#before_install:
#- openssl aes-256-cbc -K $encrypted_1cdd98337244_key -iv $encrypted_1cdd98337244_iv
#  -in client-secret.json.enc -out client-secret.json -d
