language: node_js
notifications:
  email: false
node_js:
- 8.9.1
cache:
  directories:
  - ~/.npm
  - ~/.cache
install:
#- npm install -g karma-cli
#- npm install -g ajv@6.9.1
#- npm install -g jquery@1.9.1
- npm install
