language: node_js
notifications:
  email: false
node_js:
  - 8.9.1
cache:
  directories:
  - ~/.npm
  - ~/.cache
jobs:
  include:
  - stage: "install"
    script:
      - npm install
  - stage: "ui tests"
    script:
      - ng test --no-watch
  - stage: "deploy to azure"
    script:
      - npm run build
    deploy:
      skip_cleanup: true
      provider: azure_web_apps
      verbose: true
