language: node_js
notifications:
  email: false
node_js:
  - 8.9.1
cache:
  directories:
  - ~/.npm
  - ~/.cache
install:
  - npm install
jobs:
  include:
  - stage: "UI Tests"
    script:
    - ng test --no-watch
