language: node_js
notifications:
  email: false
node_js:
  - 8.9.1
cache:
  directories:
  - ~/.npm
  - ~/.cache
jobs:
  include:
  - stage: "install"
    script:
      - npm install
  # TODO: re enable the ui tests - currently disabled to speed up the build
  #- stage: "ui tests"
  #  script:
  #    - ng test --no-watch
  - stage: "deploy to azure"
    script:
      - npm run build
    deploy:
      provider: gae
      keyfile: client-secret.json
      project: z-sport-frontend-test
before_install:
  - openssl aes-256-cbc -K $encrypted_4ca53e5fef4b_key -iv $encrypted_4ca53e5fef4b_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar xvf credentials.tar.gz

